In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('./abalone_scaled.csv')
X = df.drop(['Rings'], axis=1)
Y = df['Rings']
X.head()

,Unnamed: 0,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Sex_F,Sex_I,Sex_M
0,0,-0.574376,-0.431938,-1.148233,-0.641812,-0.607590,-0.726218,-0.638113,0,0,1
1,1,-1.448867,-1.439814,-1.278155,-1.230626,-1.171449,-1.205581,-1.213051,0,0,1
2,2,0.050260,0.122394,-0.108855,-0.309138,-0.463243,-0.356425,-0.206910,1,0,0
3,3,-0.699303,-0.431938,-0.368699,-0.637730,-0.648188,-0.607519,-0.602180,0,0,1
4,4,-1.615437,-1.540601,-1.537999,-1.272466,-1.216557,-1.287757,-1.320852,0,1,0