In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('./abalone_scaled.csv', index_col=0)
X = df.drop(['Rings'], axis=1)
Y = df['Rings']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=40, shuffle=True)
X_train

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Sex_F,Sex_I,Sex_M
390,-0.907516,-0.835088,-1.018310,-1.034695,-0.927862,-1.105143,-0.961516,0,1,0
1651,0.591612,0.273575,0.280912,0.145994,0.263007,-0.096199,0.188359,1,0,0
261,0.383400,0.323969,-0.368699,0.074561,0.037463,-0.073373,0.224293,1,0,0
2365,0.883109,0.979088,0.670679,0.482751,0.452463,0.323813,0.547695,1,0,0
265,-0.532734,-0.280757,-0.238777,-0.386694,-0.267020,-0.255987,-0.566246,1,0,0
...,...,...,...,...,...,...,...,...,...,...
2105,0.508327,0.727119,1.190368,0.431727,0.337436,0.771218,0.332093,0,0,1
3605,-0.241237,-0.331151,-0.628544,-0.516294,-0.221911,-0.602954,-0.713574,0,1,0
3342,-0.782588,-0.784695,-1.148233,-0.996937,-1.027101,-0.872310,-0.911209,0,0,1
3066,0.966393,0.928694,0.280912,0.761340,0.901294,0.460774,0.695023,1,0,0
3400,0.050260,0.223181,-0.108855,0.103134,-0.357237,0.328379,0.080558,0,0,1